language: r

sudo: required

compiler:
  - g++

r_packages:
  - assertive
  - devtools
  - Rcpp
  - RcppArmadillo
  - BH
  - bigmemory.sri

r_github_packages:
  - kaneplusplus/bigmemory
  - cdeterman/bigalgebra
  - cdeterman/RViennaCL
  - cdeterman/gpuR

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq opencl-headers libboost-program-options-dev nvidia-current
  - cd ..
  - wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1204/x86_64/cuda-repo-ubuntu1204_7.0-28_amd64.deb
  - sudo dpkg -i cuda-repo-ubuntu1204_7.0-28_amd64.deb
  - sudo apt-get update
  - sudo apt-get install cuda
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change
